<?php

/**
 * Zone Import / Export – PowerDNS Premium
 *
 * Handles:
 *   - Exporting a zone as an RFC 1035 BIND-style zone file
 *   - Exporting a zone as CSV (name,type,ttl,content)
 *   - Importing records from a CSV upload
 *   - Basic BIND zone file parsing (subset of RFC 1035 needed for migration)
 */

if (!defined('WHMCS')) {
    die('This file cannot be accessed directly');
}

class ZoneIO
{
    /** Max records allowed in a single CSV import */
    const IMPORT_LIMIT = 500;

    // =========================================================================
    // Export
    // =========================================================================

    /**
     * Generate an RFC 1035-style BIND zone file string.
     *
     * @param  string $zone  Zone name (FQDN)
     * @param  array  $data  Full zone data from PowerDNSAPI::getZone()
     * @return string
     */
    public static function exportBIND($zone, array $data)
    {
        $zone     = rtrim($zone, '.') . '.';
        $rrsets   = $data['rrsets'] ?? [];
        $lines    = [];
        $serial   = date('Ymd') . '01';

        $lines[] = '; Zone file for ' . $zone;
        $lines[] = '; Generated by PowerDNS Premium WHMCS Module on ' . date('Y-m-d H:i:s T');
        $lines[] = '; DO NOT EDIT MANUALLY';
        $lines[] = '';
        $lines[] = '$ORIGIN ' . $zone;
        $lines[] = '$TTL 300';
        $lines[] = '';

        // SOA first
        foreach ($rrsets as $rr) {
            if (strtoupper($rr['type']) === 'SOA') {
                foreach ($rr['records'] as $rec) {
                    $lines[] = sprintf('%-40s %d IN SOA %s', $rr['name'], $rr['ttl'], $rec['content']);
                }
                $lines[] = '';
                break;
            }
        }

        // NS next
        foreach ($rrsets as $rr) {
            if (strtoupper($rr['type']) === 'NS') {
                foreach ($rr['records'] as $rec) {
                    if ($rec['disabled'] ?? false) continue;
                    $lines[] = sprintf('%-40s %d IN NS %s', $rr['name'], $rr['ttl'], $rec['content']);
                }
            }
        }
        $lines[] = '';

        // Remaining types
        $skip = ['SOA', 'NS'];
        foreach ($rrsets as $rr) {
            if (in_array(strtoupper($rr['type']), $skip, true)) continue;
            foreach ($rr['records'] as $rec) {
                if ($rec['disabled'] ?? false) continue;
                $lines[] = sprintf(
                    '%-40s %d IN %-8s %s',
                    $rr['name'],
                    $rr['ttl'],
                    strtoupper($rr['type']),
                    $rec['content']
                );
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Generate a CSV string from zone records.
     *
     * Columns: name,type,ttl,content
     */
    public static function exportCSV($zone, array $data)
    {
        $rrsets = $data['rrsets'] ?? [];
        $skip   = ['SOA'];
        $rows   = [['name', 'type', 'ttl', 'content']];

        foreach ($rrsets as $rr) {
            if (in_array(strtoupper($rr['type']), $skip, true)) continue;
            foreach ($rr['records'] as $rec) {
                if ($rec['disabled'] ?? false) continue;
                $rows[] = [$rr['name'], strtoupper($rr['type']), $rr['ttl'], $rec['content']];
            }
        }

        $buf = fopen('php://temp', 'r+');
        foreach ($rows as $row) {
            fputcsv($buf, $row);
        }
        rewind($buf);
        $csv = stream_get_contents($buf);
        fclose($buf);

        return $csv;
    }

    // =========================================================================
    // Import
    // =========================================================================

    /**
     * Parse a CSV string (uploaded file contents) into a validated record list.
     *
     * Expected columns (header row required): name, type, ttl, content
     * Columns may be in any order.
     *
     * @param  string $csv        Raw CSV content
     * @param  string $zone       Zone name (used to resolve relative names)
     * @param  array  $allowed    Allowed record types
     * @return array  ['records' => [...], 'errors' => [...]]
     *                Each record: ['name','type','ttl','content']
     *                Each error:  ['line' => int, 'message' => string]
     */
    public static function parseCSV($csv, $zone, array $allowed = null)
    {
        if ($allowed === null) {
            $allowed = ['A', 'AAAA', 'CNAME', 'MX', 'TXT', 'SRV', 'CAA', 'NS', 'PTR', 'ALIAS'];
        }

        $zone    = rtrim(strtolower(trim($zone)), '.') . '.';
        $records = [];
        $errors  = [];

        $buf  = fopen('php://temp', 'r+');
        fwrite($buf, $csv);
        rewind($buf);

        // Read header
        $header = fgetcsv($buf);
        if (!$header) {
            fclose($buf);
            return ['records' => [], 'errors' => [['line' => 1, 'message' => 'Empty file or missing header row.']]];
        }

        $header = array_map('strtolower', array_map('trim', $header));
        $colMap = array_flip($header);

        $required = ['name', 'type', 'ttl', 'content'];
        foreach ($required as $col) {
            if (!isset($colMap[$col])) {
                fclose($buf);
                return ['records' => [], 'errors' => [['line' => 1, 'message' => "Missing required column: {$col}"]]];
            }
        }

        $lineNum = 1;
        while (($row = fgetcsv($buf)) !== false) {
            $lineNum++;
            if (count($row) < count($header)) continue;
            if (implode('', $row) === '') continue; // blank line

            $name    = trim($row[$colMap['name']]);
            $type    = strtoupper(trim($row[$colMap['type']]));
            $ttl     = (int) $row[$colMap['ttl']];
            $content = trim($row[$colMap['content']]);

            // Validate type
            if (!in_array($type, $allowed, true)) {
                $errors[] = ['line' => $lineNum, 'message' => "Unsupported record type: {$type}"];
                continue;
            }

            // Validate TTL
            if ($ttl < 60 || $ttl > 2147483647) {
                $errors[] = ['line' => $lineNum, 'message' => "Invalid TTL {$ttl}; must be 60–2147483647"];
                continue;
            }

            if (empty($content)) {
                $errors[] = ['line' => $lineNum, 'message' => "Empty content on line {$lineNum}"];
                continue;
            }

            // Resolve name
            if ($name === '' || $name === '@') {
                $name = $zone;
            } elseif (substr($name, -1) !== '.') {
                $name = $name . '.' . rtrim($zone, '.') . '.';
            }

            // Auto-quote TXT if needed
            if ($type === 'TXT' && substr($content, 0, 1) !== '"') {
                $content = '"' . addslashes($content) . '"';
            }

            $records[] = ['name' => $name, 'type' => $type, 'ttl' => $ttl, 'content' => $content];

            if (count($records) >= self::IMPORT_LIMIT) {
                $errors[] = ['line' => $lineNum, 'message' => 'Import limit of ' . self::IMPORT_LIMIT . ' records reached. Remaining rows ignored.'];
                break;
            }
        }

        fclose($buf);
        return ['records' => $records, 'errors' => $errors];
    }

    /**
     * Convert a parsed record list into PowerDNS PATCH-compatible RRsets.
     * Groups records by name+type, merging contents.
     *
     * @param  array $records  From parseCSV()['records']
     * @return array RRsets ready for PowerDNSAPI::batchPatch()
     */
    public static function toRRsets(array $records)
    {
        $grouped = [];
        foreach ($records as $rec) {
            $key = $rec['name'] . '|' . $rec['type'];
            if (!isset($grouped[$key])) {
                $grouped[$key] = [
                    'name'       => $rec['name'],
                    'type'       => $rec['type'],
                    'ttl'        => $rec['ttl'],
                    'changetype' => 'REPLACE',
                    'records'    => [],
                ];
            }
            $grouped[$key]['records'][] = ['content' => $rec['content'], 'disabled' => false];
        }
        return array_values($grouped);
    }
}
